
---
spring:
  config:
    activate:
      on-profile: default
  sql:
    init:
      platform: h2
cds:
  security:
    mock:
      users[1]:
        roles:
        - admin
        name: admin
      users[0]:
        roles:
        - viewer
        name: viewer
  data-source:
    auto-config:
      enabled: false
  remote:
    services:
      '[Employment]':
        destination:
          name: Employment
        type: odata-v2
      '[Candidate]':
        destination:
          name: Candidate
        type: odata-v2
---
spring:
  config.activate.on-profile: cloud
cds:
  index-page.enabled: true
  
  sql.hana.search:
    fuzzy: true
    fuzzinessThreshold: 0.9

---
management:
  endpoint:
    health:
      show-components: always
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health
  health:
    defaults:
      enabled: false
    ping:
      enabled: true
    db:
      enabled: true
